import pytest
from pages.login_page import LoginPage
from pages.products_page import ProductsPage


class TestViewProductListings:
    """Test class for QA-2: View Product Listings"""

    # -- Generated by TC Generator --
    @pytest.mark.positive
    def test_view_product_listings_after_successful_login(self, login_page, products_page, test_data):
        """
        Test: View product listings after successful login
        Type: Positive
        Preconditions: User has valid login credentials
        """
        # Step 1: Enter valid username and password on login page
        # Expected: User is successfully logged in
        login_page.login(
            test_data["users"]["standard"]["username"],
            test_data["users"]["standard"]["password"]
        )
        login_page.assert_login_success()

        # Step 2: Navigate to product inventory page
        # Expected: All products are displayed with image, name, price, and 'Add to Cart' button for each item
        products_page.assert_products_page_displayed()
        products_page.assert_all_products_have_required_elements()

    # -- Generated by TC Generator --
    @pytest.mark.positive
    def test_product_images_load_correctly(self, logged_in, products_page):
        """
        Test: Product images load correctly
        Type: Positive
        Jira Story: QA-2 - View Product Listings
        
        Preconditions: User is logged in and viewing product listings page
        Steps:
            1. Verify all product images load properly
        Expected: All product images display correctly without broken image placeholders
        """
        # User is already logged in via logged_in fixture and on products page
        
        # Verify all product images load properly without broken image placeholders
        products_page.assert_all_product_images_loaded()
