# Generated by TC Generator - Review selectors before running
import pytest
from playwright.sync_api import expect

from pages.login_page import LoginPage



class TestLogin:

    def test_sucessful_standard_user_login(self, login_page, test_data):
        # Precondition: User has a valid account

        # Enter valid credentials and login
        login_page.login(
            test_data["users"]["standard"]["username"],
            test_data["users"]["standard"]["password"],
        )

        # Verify redirected to products page
        login_page.assert_login_success()

    # -- Generated by TC Generator --
    @pytest.mark.positive
    @pytest.mark.login
    def test_successful_login_with_valid_credentials(self, login_page: LoginPage, test_data: dict):
        """
        QA-1: User should be able to log in
        Test: Successful login with valid credentials
        
        Preconditions: User is on login page
        """
        # Step 1: Enter username in username field
        # Expected: Username is entered in the field
        login_page.enter_username(test_data["users"]["standard"]["username"])
        
        # Step 2: Enter password in password field
        # Expected: Password is entered and masked
        login_page.enter_password(test_data["users"]["standard"]["password"])
        
        # Step 3: Click Login button
        # Expected: User is redirected to dashboard page
        login_page.click_login_button()
        
        # Assert successful login - user is redirected to dashboard
        login_page.assert_login_success()
