import pytest
from pages.login_page import LoginPage
from pages.products_page import ProductsPage


class TestViewProductListings:
    """Test class for QA-2: View Product Listings"""

    # -- Generated by TC Generator --
    @pytest.mark.positive
    def test_view_product_listings_after_successful_login(self, login_page, products_page, test_data):
        """
        Test: View product listings after successful login
        Type: Positive
        Preconditions: User has valid login credentials
        """
        # Step 1: Enter valid username and password on login page
        # Expected: User is successfully logged in
        login_page.login(
            test_data["users"]["standard"]["username"],
            test_data["users"]["standard"]["password"]
        )
        login_page.assert_login_success()

        # Step 2: Navigate to product inventory page
        # Expected: All products are displayed with image, name, price, and 'Add to Cart' button for each item
        products_page.assert_products_page_displayed()
        products_page.assert_all_products_have_required_elements()
