import pytest
from playwright.sync_api import expect

from pages.products_page import ProductsPage
from pages.cart_page import CartPage
from pages.login_page import LoginPage


# -- Generated by TC Generator --
@pytest.mark.positive
@pytest.mark.cart
def test_add_multiple_different_products_to_cart(
    logged_in,
    products_page,
    test_data
):
    """
    QA-3: Add Item to Cart
    Test: Add multiple different products to cart
    Verify that user can add multiple different products to cart
    and cart badge updates correctly for each addition.
    """
    # Get product names from test data
    products_to_add = test_data["products"]["multiple_items"]
    
    # Step 1: Click 'Add to Cart' for first product
    # Expected: First product button changes to 'Remove' and cart badge shows 1
    products_page.add_product_to_cart(products_to_add[0])
    products_page.assert_product_button_text(products_to_add[0], "Remove")
    products_page.assert_cart_badge_count(1)
    
    # Step 2: Click 'Add to Cart' for second product
    # Expected: Second product button changes to 'Remove' and cart badge shows 2
    products_page.add_product_to_cart(products_to_add[1])
    products_page.assert_product_button_text(products_to_add[1], "Remove")
    products_page.assert_cart_badge_count(2)
    
    # Step 3: Click 'Add to Cart' for third product
    # Expected: Third product button changes to 'Remove' and cart badge shows 3
    products_page.add_product_to_cart(products_to_add[2])
    products_page.assert_product_button_text(products_to_add[2], "Remove")
    products_page.assert_cart_badge_count(3)


# -- Generated by TC Generator --
@pytest.mark.positive
def test_view_cart_with_added_products(
    logged_in,
    products_page,
    cart_page,
    test_data
):
    """
    Test: View cart with added products
    Jira Story: QA-4 - View Cart Contents
    Type: Positive
    
    Preconditions: User is on the website and cart contains at least one product
    
    Steps:
    1. Add a product to cart
    2. Click on the cart icon
    3. Verify cart page opens and displays list of all added products 
       with correct names, prices, quantities, and images
    """
    # Precondition: Add at least one product to cart
    product_name = test_data["products"]["standard"]["name"]
    product_price = test_data["products"]["standard"]["price"]
    
    products_page.add_product_to_cart(product_name)
    
    # Step 1: Click on the cart icon
    products_page.go_to_cart()
    
    # Expected: Cart page opens and displays list of all added products
    # with correct names, prices, quantities, and images
    cart_page.assert_cart_page_loaded()
    cart_page.assert_product_in_cart(product_name)
    cart_page.assert_product_price(product_name, product_price)
    cart_page.assert_product_quantity(product_name, test_data["cart"]["7"])


# -- Generated by TC Generator --
@pytest.mark.positive
def test_view_cart_with_multiple_products(
    logged_in,
    products_page,
    cart_page,
    test_data
):
    """
    Test: View cart with multiple added products
    Jira Story: QA-4 - View Cart Contents
    Type: Positive
    
    Preconditions: User is on the website and cart contains multiple products
    
    Steps:
    1. Add multiple products to cart
    2. Click on the cart icon
    3. Verify cart page displays all added products with correct details
    """
    # Precondition: Add multiple products to cart
    products = test_data["products"]["multiple"]
    
    for product in products:
        products_page.add_product_to_cart(product["name"])
    
    # Step 1: Click on the cart icon
    products_page.go_to_cart()
    
    # Expected: Cart page opens and displays all products with correct details
    cart_page.assert_cart_page_loaded()
    cart_page.assert_cart_item_count(len(products))
    
    for product in products:
        cart_page.assert_product_in_cart(product["name"])
        cart_page.assert_product_price(product["name"], product["price"])
        cart_page.assert_product_quantity(product["name"], test_data["cart"]["default_quantity"])


# -- Generated by TC Generator --
@pytest.mark.edge_case
@pytest.mark.cart
def test_view_empty_cart(
    logged_in,
    cart_page,
    test_data
):
    """
    Test: View empty cart
    Type: Edge Case
    Jira Story: QA-4 - View Cart Contents
    Preconditions: User is logged in and cart is empty
    """
    # Step 1: Click on cart icon
    # Action: Click on cart icon
    # Expected: Cart page opens and displays empty cart message or placeholder indicating no items are in cart
    cart_page.goto()
    cart_page.assert_cart_is_empty()


# -- Generated by TC Generator --
@pytest.mark.positive
@pytest.mark.cart
def test_remove_product_from_cart(
    logged_in,
    products_page,
    test_data
):
    """
    Test: Remove product from cart
    Type: Positive
    Jira Story: QA-3 - Add Item to Cart
    Preconditions: User is logged in and has one product in cart
    """
    # Precondition: Add a product to cart first
    product_name = test_data["products"]["standard"]["name"]
    products_page.add_product_to_cart(product_name)
    
    # Step 1: Navigate to product listing page
    # Expected: Product page displays with previously added product showing 'Remove' button
    products_page.goto()
    products_page.assert_product_button_text(product_name, "Remove")
    
    # Get initial cart badge count
    initial_cart_count = products_page.get_cart_badge_count()
    
    # Step 2: Click 'Remove' button
    # Expected: 'Remove' button changes back to 'Add to Cart' and cart badge decrements by 1
    products_page.remove_product_from_cart(product_name)
    products_page.assert_product_button_text(product_name, "Add to cart")
    if initial_cart_count - 1 == 0:
        products_page.assert_cart_badge_not_visible()
    else:
        products_page.assert_cart_badge_count(initial_cart_count - 1)


# -- Generated by TC Generator --
@pytest.mark.edge_case
@pytest.mark.cart
def test_cart_badge_shows_zero_when_no_items_in_cart(
    login_page,
    products_page,
    test_data
):
    """
    Test: Cart badge shows zero when no items in cart
    Type: Edge Case
    Preconditions: User is logged in and viewing product listings page with empty cart
    
    Verifies that the cart badge shows 0 or is not visible when the cart is empty.
    """
    # Login with standard user
    login_page.login(
        test_data["users"]["standard"]["username"],
        test_data["users"]["standard"]["password"]
    )
    login_page.assert_login_success()
    
    # Verify we are on the products page with an empty cart
    # Cart badge should show 0 or not be visible when cart is empty
    products_page.assert_cart_badge_not_visible()


# -- Generated by TC Generator --
@pytest.mark.positive
@pytest.mark.cart
def test_successfully_add_product_to_cart_updates_button_and_badge(
    logged_in,
    products_page,
    test_data
):
    """
    Test: Successfully add product to cart updates button and badge
    Type: Positive
    Jira Story: QA-3 - Add Item to Cart
    
    Preconditions: User is logged in and viewing product listings
    """
    # Get initial cart badge count (should be 0 or not present)
    initial_cart_count = products_page.get_cart_badge_count()
    
    # Step 1: Click 'Add to Cart' button on a product
    # Expected: Product is added to cart, button changes to 'Remove' button, and cart badge count increases by 1
    product_name = test_data["products"]["standard"]["name"]
    products_page.add_product_to_cart(product_name)
    
    # Verify button changed to 'Remove'
    products_page.assert_product_button_text(product_name, "Remove")
    
    # Verify cart badge count increased by 1
    expected_cart_count = initial_cart_count + 1
    products_page.assert_cart_badge_count(expected_cart_count)


# -- Generated by TC Generator --
@pytest.mark.edge_case
@pytest.mark.cart
def test_rapid_multiple_clicks_on_add_to_cart_button(
    logged_in,
    products_page,
    cart_page,
    test_data
):
    """
    Test: Rapid multiple clicks on Add to Cart button
    Type: Edge Case
    Preconditions: User is on product page with empty cart
    
    Verifies that rapidly clicking Add to Cart button multiple times
    only adds the product once to the cart.
    """
    # Get the first product to test with
    product_name = test_data["products"]["standard"]["name"]
    
    # Rapidly click the Add to Cart button multiple times in quick succession
    # Simulate rapid clicks by calling add_product_to_cart multiple times without waiting
    for _ in range(5):
        products_page.add_product_to_cart(product_name)
    
    # Verify product is added only once - button should change to 'Remove'
    products_page.assert_product_button_text(product_name, "Remove")
    
    # Verify cart badge shows correct count of 1
    products_page.assert_cart_badge_count(1)
    
    # Navigate to cart and verify only one item exists
    products_page.go_to_cart()
    cart_page.assert_item_in_cart(product_name)
    cart_page.assert_cart_item_count(1)