# Generated by TC Generator - Review selectors before running
import pytest
from playwright.sync_api import expect

from pages.login_page import LoginPage
from pages.products_page import ProductsPage



class TestLogin:

    def test_sucessful_standard_user_login(self, login_page, test_data):
        # Precondition: User has a valid account

        # Enter valid credentials and login
        login_page.login(
            test_data["users"]["standard"]["username"],
            test_data["users"]["standard"]["password"],
        )

        # Verify redirected to products page
        login_page.assert_login_success()

    # -- Generated by TC Generator --
    @pytest.mark.positive
    @pytest.mark.login
    def test_successful_login_with_valid_credentials(self, login_page, test_data):
        """
        QA-1: User should be able to log in
        Test: Successful login with valid credentials
        
        Preconditions: User is on login page
        """
        # Step 1: Enter username in username field
        # Expected: Username is entered in the field
        login_page.enter_username(test_data["users"]["standard"]["username"])
        
        # Step 2: Enter password in password field
        # Expected: Password is entered and masked
        login_page.enter_password(test_data["users"]["standard"]["password"])
        
        # Step 3: Click Login button
        # Expected: User is redirected to dashboard page
        login_page.click_login_button()
        
        # Assert successful login - user is redirected to dashboard
        login_page.assert_login_success()

    # -- Generated by TC Generator --
    @pytest.mark.negative
    @pytest.mark.login
    def test_login_failure_with_invalid_username(self, login_page, test_data):
        """
        Test: Login failure with invalid username
        Type: Negative
        Jira Story: QA-1 - User should be able to log in
        Preconditions: Login page is displayed
        """
        # Step 1: Enter invalid username in username field
        # Expected: Username is entered and displayed in the field
        login_page.enter_username(test_data["users"]["invalid"]["username"])
        
        # Step 2: Enter valid password in password field
        # Expected: Password is entered and masked in the field
        login_page.enter_password(test_data["users"]["standard"]["password"])
        
        # Step 3: Click login button
        # Expected: Error message is displayed indicating invalid credentials and user remains on login page
        login_page.click_login_button()
        
        # Assert error message is displayed
        login_page.assert_error_message(test_data["errors"]["invalid_credentials"])

    # -- Generated by TC Generator --
    @pytest.mark.negative
    @pytest.mark.login
    def test_login_fails_with_invalid_password(self, login_page, test_data):
        """
        Test: Login fails with invalid password
        Jira Story: QA-1 - User should be able to log in
        Type: Negative
        """
        # Precondition: Login page is displayed (handled by login_page fixture)
        
        # Step 1: Enter valid username in username field
        login_page.enter_username(test_data["users"]["standard"]["username"])
        
        # Step 2: Enter invalid password in password field
        login_page.enter_password(test_data["users"]["invalid"]["password"])
        
        # Step 3: Click login button
        login_page.click_login_button()
        
        # Expected: Error message is displayed indicating invalid credentials and user remains on login page
        login_page.assert_error_message(test_data["errors"]["invalid_credentials"])
        login_page.assert_on_login_page()


class TestLogout:
    """Test cases for QA-5: Log Out"""

    # -- Generated by TC Generator --
    @pytest.mark.positive
    def test_successful_logout_from_application(self, logged_in, products_page, login_page_obj):
        """
        Test: Successful logout from application
        Type: Positive
        Preconditions: User is logged in and on any page of the application
        Steps:
          1. Click the logout link/menu option
          Expected: System redirects to login page and user session is terminated
        """
        # User is already logged in via the logged_in fixture
        # Step 1: Click the logout link/menu option

        products_page.logout()
        
        # Expected: System redirects to login page and user session is terminated
        logged_in.assert_logout_success()
