import pytest
from playwright.sync_api import expect

from pages.products_page import ProductsPage
from pages.cart_page import CartPage


# -- Generated by TC Generator --
@pytest.mark.positive
@pytest.mark.cart
def test_add_multiple_different_products_to_cart(
    logged_in,
    products_page: ProductsPage,
    test_data: dict
):
    """
    QA-3: Add Item to Cart
    Test: Add multiple different products to cart
    Verify that user can add multiple different products to cart
    and cart badge updates correctly for each addition.
    """
    # Get product names from test data
    products_to_add = test_data["products"]["multiple_items"]
    
    # Step 1: Click 'Add to Cart' for first product
    # Expected: First product button changes to 'Remove' and cart badge shows 1
    products_page.add_product_to_cart(products_to_add[0])
    products_page.assert_product_button_text(products_to_add[0], "Remove")
    products_page.assert_cart_badge_count(1)
    
    # Step 2: Click 'Add to Cart' for second product
    # Expected: Second product button changes to 'Remove' and cart badge shows 2
    products_page.add_product_to_cart(products_to_add[1])
    products_page.assert_product_button_text(products_to_add[1], "Remove")
    products_page.assert_cart_badge_count(2)
    
    # Step 3: Click 'Add to Cart' for third product
    # Expected: Third product button changes to 'Remove' and cart badge shows 3
    products_page.add_product_to_cart(products_to_add[2])
    products_page.assert_product_button_text(products_to_add[2], "Remove")
    products_page.assert_cart_badge_count(3)
