import pytest
from playwright.sync_api import expect

from pages.products_page import ProductsPage
from pages.cart_page import CartPage


# -- Generated by TC Generator --
@pytest.mark.positive
@pytest.mark.cart
def test_add_multiple_different_products_to_cart(
    logged_in,
    products_page: ProductsPage,
    test_data: dict
):
    """
    QA-3: Add Item to Cart
    Test: Add multiple different products to cart
    Verify that user can add multiple different products to cart
    and cart badge updates correctly for each addition.
    """
    # Get product names from test data
    products_to_add = test_data["products"]["multiple_items"]
    
    # Step 1: Click 'Add to Cart' for first product
    # Expected: First product button changes to 'Remove' and cart badge shows 1
    products_page.add_product_to_cart(products_to_add[0])
    products_page.assert_product_button_text(products_to_add[0], "Remove")
    products_page.assert_cart_badge_count(1)
    
    # Step 2: Click 'Add to Cart' for second product
    # Expected: Second product button changes to 'Remove' and cart badge shows 2
    products_page.add_product_to_cart(products_to_add[1])
    products_page.assert_product_button_text(products_to_add[1], "Remove")
    products_page.assert_cart_badge_count(2)
    
    # Step 3: Click 'Add to Cart' for third product
    # Expected: Third product button changes to 'Remove' and cart badge shows 3
    products_page.add_product_to_cart(products_to_add[2])
    products_page.assert_product_button_text(products_to_add[2], "Remove")
    products_page.assert_cart_badge_count(3)


# -- Generated by TC Generator --
@pytest.mark.positive
def test_view_cart_with_added_products(
    logged_in,
    products_page: ProductsPage,
    cart_page: CartPage,
    test_data: dict
):
    """
    Test: View cart with added products
    Jira Story: QA-4 - View Cart Contents
    Type: Positive
    
    Preconditions: User is on the website and cart contains at least one product
    
    Steps:
    1. Add a product to cart
    2. Click on the cart icon
    3. Verify cart page opens and displays list of all added products 
       with correct names, prices, quantities, and images
    """
    # Precondition: Add at least one product to cart
    product_name = test_data["products"]["standard"]["name"]
    product_price = test_data["products"]["standard"]["price"]
    
    products_page.add_product_to_cart(product_name)
    
    # Step 1: Click on the cart icon
    products_page.click_cart_icon()
    
    # Expected: Cart page opens and displays list of all added products
    # with correct names, prices, quantities, and images
    cart_page.assert_cart_page_loaded()
    cart_page.assert_product_in_cart(product_name)
    cart_page.assert_product_price(product_name, product_price)
    cart_page.assert_product_quantity(product_name, test_data["cart"]["default_quantity"])


# -- Generated by TC Generator --
@pytest.mark.positive
def test_view_cart_with_multiple_products(
    logged_in,
    products_page: ProductsPage,
    cart_page: CartPage,
    test_data: dict
):
    """
    Test: View cart with multiple added products
    Jira Story: QA-4 - View Cart Contents
    Type: Positive
    
    Preconditions: User is on the website and cart contains multiple products
    
    Steps:
    1. Add multiple products to cart
    2. Click on the cart icon
    3. Verify cart page displays all added products with correct details
    """
    # Precondition: Add multiple products to cart
    products = test_data["products"]["multiple"]
    
    for product in products:
        products_page.add_product_to_cart(product["name"])
    
    # Step 1: Click on the cart icon
    products_page.click_cart_icon()
    
    # Expected: Cart page opens and displays all products with correct details
    cart_page.assert_cart_page_loaded()
    cart_page.assert_cart_item_count(len(products))
    
    for product in products:
        cart_page.assert_product_in_cart(product["name"])
        cart_page.assert_product_price(product["name"], product["price"])
        cart_page.assert_product_quantity(product["name"], test_data["cart"]["default_quantity"])
