# Generated by TC Generator - Review selectors before running
import pytest
from pages.login_page import LoginPage


class TestLogin:

    def test_invalid_user_login(self, login_page, test_data):
        # Precondition: User has a valid account

        # Enter valid credentials and login
        login_page.login(
            test_data["users"]["standard"]["username"],
            test_data["users"]["standard"]["password"],
        )

        # Verify redirected to products page
        login_page.assert_login_success()


