import re
from playwright.sync_api import Page, expect
from pages.base_page import BasePage


class ProductsPage(BasePage):

    def __init__(self, page: Page):
        super().__init__(page)
        self.page_title = page.locator(".title")
        self.inventory_items = page.locator(".inventory_item")
        self.cart_badge = page.locator(".shopping_cart_badge")
        self.cart_link = page.locator(".shopping_cart_link")
        self.sort_dropdown = page.locator('[data-test="product_sort_container"]')

    def goto(self):
        self.navigate_to("/inventory.html")

    def get_product_card(self, product_name: str):
        return self.page.locator(".inventory_item").filter(has_text=product_name)

    def add_product_to_cart(self, product_name: str):
        product_card = self.get_product_card(product_name)
        product_card.locator("button").click()

    def remove_product_from_cart(self, product_name: str):
        product_card = self.get_product_card(product_name)
        product_card.locator("button").click()

    def get_product_button_text(self, product_name: str) -> str:
        product_card = self.get_product_card(product_name)
        return product_card.locator("button").inner_text()

    def get_cart_badge_count(self) -> int:
        if self.cart_badge.is_visible():
            return int(self.cart_badge.inner_text())
        return 0

    def go_to_cart(self):
        self.cart_link.click()

    def get_all_product_names(self) -> list:
        return self.page.locator(".inventory_item_name").all_inner_texts()

    def get_product_price(self, product_name: str) -> str:
        product_card = self.get_product_card(product_name)
        return product_card.locator(".inventory_item_price").inner_text()

    def assert_on_products_page(self):
        expect(self.page).to_have_url(re.compile(r".*inventory.*"))
        expect(self.page_title).to_have_text("Products")

    def assert_product_button_text(self, product_name: str, expected_text: str):
        product_card = self.get_product_card(product_name)
        expect(product_card.locator("button")).to_have_text(expected_text)

    def assert_cart_badge_count(self, count: int):
        if count == 0:
            expect(self.cart_badge).not_to_be_visible()
        else:
            expect(self.cart_badge).to_have_text(str(count))

    def assert_cart_badge_not_visible(self):
        expect(self.cart_badge).not_to_be_visible()

    # -- Generated by TC Generator --
    def click_cart_icon(self):
        """Click on the cart icon to navigate to cart page"""
        self.cart_link.click()

    # -- Generated by TC Generator --
    def assert_products_page_displayed(self):
        """Assert that the products page is displayed"""
        expect(self.page).to_have_url(re.compile(r".*inventory.*"))
        expect(self.page_title).to_have_text("Products")

    # -- Generated by TC Generator --
    def assert_all_products_have_required_elements(self):
        """Assert that all products have image, name, price, and Add to Cart button"""
        items = self.inventory_items.all()
        assert len(items) > 0, "No products found on the page"
        for item in items:
            # Check for product image
            expect(item.locator("img.inventory_item_img")).to_be_visible()
            # Check for product name
            expect(item.locator(".inventory_item_name")).to_be_visible()
            # Check for product price
            expect(item.locator(".inventory_item_price")).to_be_visible()
            # Check for Add to Cart button
            expect(item.locator("button")).to_be_visible()
